### ISSUE TITLE
Local installation: MySQL/MariaDB instructions are incomplete

### ISSUE THREAD

**Issue by fthommen** [proteomicsunitcrg/qcloud2-pipeline#53]
Hi,

the instructions on https://github.com/proteomicsunitcrg/qcloud2-pipeline/tree/local are missing the point, that the initial database (_database_name_) has to be created _before_ the service is started the first time.  I.e. the instructions at "1. Create a MySQL QCloud user, for instance:" should probably rather read

1. Create a MySQL/MariaDB QCloud user and database, for instance:
```mysql
CREATE USER 'qcloud_user'@'%' IDENTIFIED BY 'password_here';
CREATE database database_name;
GRANT ALL PRIVILEGES ON * . * TO 'qcloud_user'@'%';
FLUSH PRIVILEGES;
```
Maybe - for enhanced security and privacy - the permissions for "qcloud_user" could be restricted to the QCloud database:
```mysql
GRANT ALL PRIVILEGES ON database_name.* TO 'qcloud_user'@'%';
```
(untested).

Also the prerequisite "mysql-server >= 14.14" should probably be adapted in times where MariaDB has taken MySQLs place in many or most Linux distributions :-).

**Comment by rolivella** [comment]
Yep, you are right, thank you for letting me know. Regarding MariaDB, we only put the prerequisites that we had tested previously. Let me know if everything works properly with MariaDB and we'll add it.

**Comment by rolivella** [comment]
Changes made. Thanks for reporting.
