### ISSUE TITLE
Local Installation: HTTPS Support?

### ISSUE THREAD

**Issue by fthommen** [proteomicsunitcrg/qcloud2-pipeline#55]
Hi, is there a way to configure the local QCloud server for HTTPS or do we need to achieve this with our own reverse proxy?

**Comment by rolivella** [comment]
I'm not sure, @MarcSerretCRG could you answer this question?

**Comment by MarcSerretCRG** [comment]
Hi, you have to modify your server to achieve this (with apache, nginx, etc).

**Comment by fthommen** [comment]
ok, I will set up a proxy then.  Thanks
