### ISSUE TITLE
Local Installation: No country selection per keyboard in the registration form

### ISSUE THREAD

**Issue by fthommen** [proteomicsunitcrg/qcloud2-pipeline#56]
Hi,

in the registration form of QCloud local 1.0.22.7.2, the country cannot be selected by typing its name
![qcloud_country_selection](https://user-images.githubusercontent.com/279232/101500315-98f04100-396e-11eb-876a-6724a1990828.png)
IIRC, this has been possible in earlier versions

**Comment by rolivella** [comment]
Thanks for the suggestion, we'll try to include this feature in future releases.
