### ISSUE TITLE
Local Installation: Confusing texts in buttons and menues

### ISSUE THREAD

**Issue by fthommen** [proteomicsunitcrg/qcloud2-pipeline#57]
Hi, in QCloud 1.0.22.7.2 (local installation) I see this text in the registration "send" button:
![qcloud_registration_send](https://user-images.githubusercontent.com/279232/101503594-8bd55100-3972-11eb-8293-a2d4295d91f4.png)

and these items in the QCloud menu
![qcloud_menu_items](https://user-images.githubusercontent.com/279232/101503616-909a0500-3972-11eb-8cbf-98a6dabb8d53.png)

Which rather look like tags or labels than like menu entries or button texts.

**Comment by rolivella** [comment]
@MarcSerretCRG could you have a look at this? Thanks.

**Comment by MarcSerretCRG** [comment]
Hi, now the icons are loaded locally, are you blocking the assets?

**Comment by fthommen** [comment]
It's a fresh browser profile, no blocking (other what Firefox does by default), no plugins

**Comment by rolivella** [comment]
@fthommen, @MarcSerretCRG  is out of the office till next thursday. He told me that's not able to reproduce you error. He removed all the CDNs dependencies so now every image should be uploaded locally.Maybe if you paste an screenshot like this we'll figure out what's happening: 

![screenshot](https://user-images.githubusercontent.com/1679820/101894329-50bb6380-3ba6-11eb-9a62-07a16ec41ce7.png)

**Comment by fthommen** [comment]
That's what I can offer :-).  The pop-up with the object information doesn't show in my firefox (developer edition 84.0b). Maybe an additional add-on is required?

![qcloud_web_inspector](https://user-images.githubusercontent.com/279232/101910948-f929f180-3bbf-11eb-960a-ad1c63790e0a.png)

**Comment by rolivella** [comment]
@fthommen could we close this issue? Thanks.

**Comment by fthommen** [comment]
The situation hasn't changed and the confusing texts are still here

**Comment by MarcSerretCRG** [comment]
Can you provide a screenshot showing the network requests please?

**Comment by fthommen** [comment]
I will send you the screenshot by personal mail

**Comment by rolivella** [comment]
We didn't received the screenshot...

**Comment by fthommen** [comment]
Resent to Marc from my office address. First mail had been from "Sat, 20 Feb 2021 15:23:14". Let me know (to my office address) if it arrived this time

**Comment by rolivella** [comment]
(@MarcSerretCRG could you please take care of it? Thanks!)

Message from @fthommen: 

it seems that QCloud2 does indeed use websockets.  I tried to configure
the proxy accordingly and tried with /api and /api/gs-guide-websocket as
locations in the websocket URL.  None of these seems to work and the UI
also always reports "API status: DOWN".

However I am not sure if the access denial for the fonts is related to
that problem, as these seem to be straightforward URLs.  You say that
you tried this with a reverse proxy on your site and that you can't
reproduce the error?

**Comment by MarcSerretCRG** [comment]
The message at intranet "API status: DOWN" talks about the QCloud2 public api, not the backend. The next local version jar will have removed this message.
About the websocket i dont know. I just use Apache to reverse proxy the jar embeded tomcat server.

**Comment by fthommen** [comment]
The issue with the icons has been solved by the newest jar file release.  Thanks a lot
