### ISSUE TITLE
Change Qcloud2 local server address from localhost to particular server name

### ISSUE THREAD

**Issue by nara3m** [proteomicsunitcrg/qcloud2-pipeline#60]
Hey @rolivella 

Thanks for developing local version of qCloud2. As you rightly predicted, localhost is not possible because the server is remote. where can I change server name ?

Cheers!

**Comment by rolivella** [comment]
OK @nara3m . Please @MarcSerretCRG , could you help Nara with this by private mail? Thanks.

**Comment by rolivella** [comment]
Fixed.
