### ISSUE TITLE
Local Installation Error

### ISSUE THREAD

**Issue by xLinkKnight** [proteomicsunitcrg/qcloud2-pipeline#74]
Attempting to install QCloud2 on a system running CentOS7. I've installed the prerequisite packages, MySQL, Java, Nextflow, Docker, and the Singularity container.

I've attached the output for when we attempt to run the ```QCloud2-1.0.23LOCAL``` jar file with the edited .yml file. I'm not familiar with the readout, so I can't diagnose what the issue(s). It seems related to login access issue, due to an incorrectly configured host. No changes to MySQL were made after it's installation. We just ensured that it was active and running.

[Log.txt](https://github.com/proteomicsunitcrg/qcloud2-pipeline/files/7981515/Log.txt)
[external_config.yml.txt](https://github.com/proteomicsunitcrg/qcloud2-pipeline/files/7981524/external_config.yml.txt)

**Comment by xLinkKnight** [comment]
Further information. I believe we had incorrectly created the MySQL database. We rectified the issue and came across a different error when attempting to start the server. The log file is attached.

[ErrorLog.txt](https://github.com/proteomicsunitcrg/qcloud2-pipeline/files/7997237/ErrorLog.txt)

We see the ```Public Key Retrieval is not allowed``` error message. We thought the ```useSSL=false``` statement in the ```external_config.yml``` file would resolve this requirement. Not sure if this is the root issue, but any help would be appreciated.

**Comment by xLinkKnight** [comment]
I added ```allowPublicKeyRetrieval=true``` to the url and was able to get further into the website installation. 

We now run into an error pointing to:

```Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'qcloud.threshold.min-points-guideset' in value "${qcloud.threshold.min-points-guideset}"```

Log attached: [ErrorLog2.txt](https://github.com/proteomicsunitcrg/qcloud2-pipeline/files/7997426/ErrorLog2.txt)

**Comment by xLinkKnight** [comment]
We were able to access the QCloud website at http://localhost:8089 once we added ```min-points-guideset: 3``` to the ```qcloud``` block of the .yml config file.

But we are unable to log in using our credentials (username and password in .yml file). The page will say "Connecting..." for a while and then respond with "Unable to connect with QCloud2 servers". 

We're not sure how to proceed and troubleshoot this issue.

**Comment by rolivella** [comment]
@xLinkKnight let me have a look at that and I let you know ASAP.

**Comment by xLinkKnight** [comment]
Just one last update. We were able to use the beta java version (QCloud2-1.0.22.7.2OUTSIDE) and get access to the website. The issue with that route was that many of the website functions seemed broken or inaccessible.

**Comment by rolivella** [comment]
Could double check this step?

> Once the server is up, open http://localhost:8089/ in your browser (Firefox or Google Chrome) and log in with the email you put in the YML file under the field admin-email. Currently the 8089 cannot be changed. But if you're experencing some issue with the localhost, we can change it to your particular server address. To do that please open a new issue in this current repository.

**Comment by rolivella** [comment]
@xLinkKnight any news about your installation? Otherwise I'll close this issue. Thanks.
